str = "Iam studying python from Apnacollege."
print(str.endswith("app"))
print(str.endswith("Apnacollege."))
print(str.capitalize())
print(str.upper())
print(str.lower())
print(str.isnumeric())
print(str.replace("Apnacollege","College"))
print(str.startswith("Iam"))
print(str.find("python"))
print(str.endswith("Apnacollege."))
print(str.upper())
print(str.lower())
print(str.find("from"))
print(str.replace("from","in"))
print(str.count("o"))

name = input("Enter the first name of user:  ")
print(len(name))